[workspace]
members = [
    "crates/sylver-core",
    "crates/sylver-cli",
    "crates/sylver-langs",
    "crates/sylver-dsl",
    "crates/sylver-script",
    "crates/log",
]

[profile.release]
debug = 0